name: BuildAndPublish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  
  build-domain:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Domain dependencies
        run: dotnet restore KarizmaShop.Domain/KarizmaShop.Domain.csproj

      - name: Build Domain project
        run: dotnet build KarizmaShop.Domain/KarizmaShop.Domain.csproj --configuration Release --no-restore

      - name: Pack Domain project
        run: dotnet pack KarizmaShop.Domain/KarizmaShop.Domain.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish Domain package to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.KARIZMASHOP_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.KARIZMASHOP_API_KEY }}
  
  
  build-application:
    runs-on: ubuntu-latest
    needs: build-domain

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Application dependencies
        run: dotnet restore KarizmaShop.Application/KarizmaShop.Application.csproj

      - name: Build Application project
        run: dotnet build KarizmaShop.Application/KarizmaShop.Application.csproj --configuration Release --no-restore

      - name: Pack Application project
        run: dotnet pack KarizmaShop.Application/KarizmaShop.Application.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish Application package to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.KARIZMASHOP_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.KARIZMASHOP_API_KEY }}